### POST request to create patient
POST http://localhost:4004/api/patients
Content-Type: application/json
Accept-Language: fr-FR

{
  "name": "Amine Benzaggagh",
  "email": "ab3333@example.com",
  "address": "001 Main Street",
  "dateOfBirth": "1998-02-14"
}

###