### POST request to create patient
POST http://lb-2d8b6a25.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Accept-Language: fr-FR
Authorization: Bearer {{ token }}

{
  "name": "Amine Benzaggagh",
  "email": "ab3333@example.com",
  "address": "001 Main Street",
  "dateOfBirth": "1998-02-14"
}

###