### PUT request to update a patient
PUT http://localhost:4004/api/patients/9e42d0f2-dafb-463d-80ef-5d07ddafb19c
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "Amine BEN ZAGGAGH",
  "email": "amine.benzaggagh@example.com",
  "address": "001 Main Street",
  "dateOfBirth": "1998-02-14"
}

###